### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [GabiBrawl/SPOTYdl#1]
please can you help me how can I run this programm on cmd?

**Comment by GabiBrawl** [comment]
If you have already installed spotDL, download this file https://github.com/GabiBrawl/SPOTYdl/blob/main/server/script.bat copy it to an empty folder, the double tap it.

If you didn't install yet spotDL, download https://github.com/GabiBrawl/SPOTYdl/releases/tag/v1.4.1 extract the zip file, then run "SPOTYdl - SETUP" and everything will be setup automatically :D
If you wanna enroll to the beta, install SPOTYdl, run it and then go to the version menu and change the update channel to beta. Hope you have a great time using SPOTYdl!
![Captura de Ecrã (216)](https://user-images.githubusercontent.com/85069997/161388801-e31e21f7-06e5-4aea-af8a-b8df78114624.png)

**Comment by GabiBrawl** [comment]
Were you able to use it? If yes, please close this issue.

**Comment by GabiBrawl** [comment]
Were you able to use it? If yes, please close this issue.
