### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [GabiBrawl/SPOTYdl#2]
my friend I uninstall python for some reason and now I cant download!!!please help me!which version of python I must install and tell me which pip I need and the steps to run python and pip3 on cmd?

**Comment by GabiBrawl** [comment]
First, download python from here: https://www.python.org/ftp/python/3.10.2/python-3.10.2-amd64.exe (it's the link inside the setup file, but the setup file is not yet working correctly)
Secondly, go to the download location and run cmd in there. In there type ".\python-3.10.2-amd64.exe InstallAllUsers=1 PrependPath=1" and press enter. After some minutes, it should be installed.
Finally, Close the cmd window, then reopen it. In there type "pip install spotdl". If there was no error, congrats! You've reinstalled python and spotDL successfully!

If there was any error, tell me bellow! If not, please close the issue with a comment ;)

**Comment by KENPOKASMMA1982** [comment]
my friend thanks so much!but can you enter with teamviwer to help me please?or with anydesk?I will preciate it so much!

**Comment by GabiBrawl** [comment]
Only tomorrow, or the day after (:
I'll be using anydesk, have it prepared

**Comment by KENPOKASMMA1982** [comment]
woowwwwww thanks mate!!!please let me know when you can enter for while!!!thanks a lottttttttt!!

**Comment by GabiBrawl** [comment]
When you're ready join in anydesk with the code: 633549680
I'm going to make some food rn, I'll be back in half an hour, but join if you'd like to (:

**Comment by KENPOKASMMA1982** [comment]
heyyyyyyy...nooooooo my friend...you have to enter on my pc!pleaseeeeeeeeeeI go to open it!!!   779270404

**Comment by GabiBrawl** [comment]
oh, i've not used anydesk for some time now... lol

**Comment by KENPOKASMMA1982** [comment]
779270404

**Comment by GabiBrawl** [comment]
It's working! Ima close the conversation now ;)
