### ISSUE TITLE
The script doesnt go back to Main Menu

### ISSUE THREAD

**Issue by homebrewGT** [GabiBrawl/SPOTYdl#3]
After downloading a song (individual not playlist) the script doesn't return to the main menu. Also, it would be good to add an option to save the song format that way whenever you open the script after properly configure it you can go straight to the download section.

Maybe an automatic option to go back to download instead of main menu?

**Comment by GabiBrawl** [comment]
First of all, thank you for taking your time writing this suggestion and bug report! 


You mean that when you download a playlist, it does go back to the main menu, or you didnt test with playlists?

Imma add that as a feature really soon! It's a great idea💡

**Comment by homebrewGT** [comment]
Hey, yeah, i modified the script to allow that, i think i did a pull request for it.

**Comment by GabiBrawl** [comment]
I dont find any pull request, are you sure you did push it?
